import {
	Container,
	Box,
	Button,
	Typography,
	Grid,
	TextField,
} from '@mui/material';

const AuthToken = () => {
	return (
		<Container>
			<Box>
				<Typography>
					Please enter the One Time Password (OTP) generated by your Microsoft
					Authenticator App.
				</Typography>
				<Box sx={{ flexGrow: 1 }}>
					<Grid container spacing={2}>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
						<Grid item xs={2}>
							<TextField
								hiddenLabel
								id='filled-hidden-label-small'
								variant='outlined'
								size='small'
							/>
						</Grid>
					</Grid>
				</Box>
				<Button variant='contained'>Verify</Button>
			</Box>
		</Container>
	);
};

export default AuthToken;
